jobs:
  lint_knip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: ./.github/actions/prepare
      - run: pnpm lint:knip

name: Lint Knip

on:
  pull_request: ~
  push:
    branches:
      - main
